---
  # the relative (or absolute) path to the dialogue output file
  dialogue_filepath: "./dialogue.txt"
  raw_dialogue_filepath: "./raw_dialogue.txt"
  # The relative (or absolute) path to the screenshot output folder
  screenshot_folderpath: "./screenshots/"

  # Minimum time interval (in seconds) between datetime headers in the dialogue file
  time_header_interval: 300
  # Time between dialogue read in seconds (recommend no lower than 5 seconds)
  read_interval: 10

  # Path to your installed Tesseract exe
  tesseract_filepath: "C:/Program Files/Tesseract-OCR/tesseract.exe"

  # Confidence level for automatic image matching of chatbox
  #  0.7-0.8 is usually ok, lower may lead to improper matching
  confidence_level: 0.8

  # Make use of default regex to remove timestamps and channel tag
  use_default_regex: True

  # Extra regex to use when parsing text
  # This should be an array of tuples, the first entry being the target, 2nd the replace
  # user_regex: [ !!python/tuple ['(fo)o','\1'], !!python/tuple ['bar', 'foo'] ]
  # This regex removes a newline if the next line doesn't have a `:` in it
  user_regex: [ !!python/tuple ['\n(?!.+:)([^\n].+)','\1'] ]

  # Custom *letter* to be used as a pause/resume hotkey in combination with the "alt" key
  # Due to a bug in pynput this restriction is unfortunately needed for now
  # with hotkey: 'l', the pause hotkey would then be <alt>+l
  hotkey: l
